# fly.toml app configuration file generated for logd-twilight-wind-1658 on 2024-01-01T17:03:23+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "logd"
primary_region = "ams"

[build]
dockerfile = "fly.Dockerfile"

[env]
  BUFFER_SIZE = "100000"
  HTTP_LADDR = ":6101"
  UDP_LADDR = "fly-global-services:6102"

[[services]]
  internal_port = 6101
  protocol = "tcp"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[services]]
  internal_port = 6102
  protocol = "udp"

  [[services.ports]]
    port = 6102

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 2048
