# fly.toml app configuration file generated for logd on 2024-01-05T16:53:53+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "logd"
primary_region = "ams"

[build]
  dockerfile = "fly.Dockerfile"

[env]
  BUFFER_SIZE = "100000"
  HTTP_LADDR = ":6101"
  UDP_LADDR = "fly-global-services:6102"

[[services]]
  protocol = "tcp"
  internal_port = 6101

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[services]]
  protocol = "udp"
  internal_port = 6102

  [[services.ports]]
    port = 6102

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
