# fly.toml app configuration file generated for swi-logd on 2024-02-15T10:10:07+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'swi-logd'
primary_region = 'ams'

[build]
  dockerfile = 'fly.Dockerfile'

[deploy]
  strategy = 'immediate'

[env]
  LOGD_ACCESS_CONTROL_ALLOW_ORIGIN = '*'
  LOGD_UDP_LADDRPORT = 'fly-global-services:6102'

[[services]]
  protocol = 'tcp'
  internal_port = 6101

[[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[services]]
  protocol = 'udp'
  internal_port = 6102

[[services.ports]]
    port = 6102

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
